version: '3'

services:
  web:
    image: igossoudarev/webdocker111124:linux
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "1337:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./about.html:/usr/share/nginx/html/about.html:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
